"""add claimed_devices table

Revision ID: 4790abb394fe
Revises: 80c77da5bd08
Create Date: 2026-03-20 15:03:24.989573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4790abb394fe'
down_revision: Union[str, Sequence[str], None] = '80c77da5bd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimed_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('claim_token', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('linked', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_token'),
    sa.UniqueConstraint('mac_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claimed_devices')
    # ### end Alembic commands ###
